### ISSUE TITLE
Question: Wrapper Locking Strategy for Authentication

### ISSUE THREAD

**Issue by homestar9** [mjclemente/api-wrapper-template#4]
This is more of a question as opposed to an issue related to the API wrapper.  I've been using it for a few projects and I really like the flow so far.   I'm trying to come up with an elegant strategy here for cases where the bearer token gets purged on the 3rd party API and a wrapper needs to re-authenticate. In other words, I'm trying to make the wrapper smart enough to try again on a failed 1st attempt.

What I've done so far is modified the `apiCall()` method to include a new boolean property `retryOnTokenFailure`.
Then, if the API response returns an error with some type of matching language indicating a bad token, clear out the token and then I re-attempt `apiCall()`.  I used named locks to try and limit any chances of a race condition.

It looks a little something like this (abbreviated):

```
private struct function apiCall(
    required string httpMethod,
    required string path,
    struct queryParams = {},
    any payload = '',
    struct headers = {},
    boolean authRequired = true,
    boolean retryOnTokenFailure = true
) {
    
    // Do we need to authenticate?
    if ( 
          arguments.authRequired &&   // authentication is required
          !isValidToken()  // does the token exist and has it not expired?
    ) {

        // lock technique to prevent race conditions
        lock name="thisapi-auth" type="exclusive" timeout="30" {
          
            if ( !isValidToken() ) {  // check for a valid token again
            
                var authResult = authenticate();

                if ( !authResult.success ) {
                    return authResult;
                }

            }

        }

    }
    

    ... // make the api call and save the result as a variable called 'result'
    

    // Check for an expired token error message, and if so, clear out the token and try again;
    if ( 
        arguments.retryOnTokenFailure && // should we retry on failure?
        result.data.error && // was there an error?
        result.data.messages.findNoCase( "Expired Authentication Credentials" ) // does the error message match?
    ) {
        
        lock name="thisapi-auth" type="exclusive" timeout="30" {
            clearAuth(); // force auth to reset (clears out the auth token)
        }
        
        arguments.retryOnTokenFailure = false; // make sure we don't run an infinite loop
        result = apiCall( argumentCollection = arguments );

    }

    return result;
}
```

I'm not 100% confident that the `clearAuth()` and `authenticate()` process is completely free from any race conditions, but I would be curious to hear your feedback or opinion on whether you have a preferred strategy for handling API call re-attempts?  Also, I wonder if something like this would be a nice addition to the wrapper template you created, or if it increases the complexity too much?

**Comment by mjclemente** [comment]
Thanks for opening this!

It's a really good question / issue. When I put this together, I hadn't had much experience with APIs doing token based authentication. I still have really only worked on one. Let me take a look at what I did there, combined with your code, and see what I come up with.

I agree that it would be really helpful if it could be included somehow, as an option in the scaffolding process.

Might take me a few days - got a lot going on right now 😄

**Comment by mjclemente** [comment]
Ok, finally had the chance to circle back around to this, though I'm not sure how helpful this response is going to be, because I haven't had enough experience working with different APIs that require this flow.

Here's the one instance where I needed to use a refresh-token flow: https://gist.github.com/mjclemente/824f58d52ed907b1fcf18789fdee80a2

(It's a Salesforce wrapper, originally written by Dan Watt, then updated by Jeremy Halliwell, and finally modified by me... so most of the code/flow isn't mine, I was just working with an existing process).

It's generally similar to your flow. 

Some differences:

- **Application-scoped lock instead of named lock**. I'm not an expert in locking, and I'm not entirely sure which approach is more appropriate here. It probably depends on the use case. That said, I'm inclined to lean toward your approach with a named lock, but we'd need a way to ensure that it was unique and applicable to this CFC instance only, since it's server-wide.
- **Separate function for refreshing token**. I think prefer this approach for code organization and separation (though I'd probably name the function something different than `logIn()`, like it's named here.
- **Only locking once**. Within the function to refresh the token, the lock is issued once. If it's successful, it sets the new token, if it's not, it clears it. No need to re-lock to clear the token.

If an API used this type of flow (it's typical for OAuth, right?), I don't think I'd set it up with a `retryOnTokenFailure` - I think I'd make it automatic.

Thoughts? As someone working with this type of API, I'd be interested in hearing your take. I feel a bit hampered by my lack of experience with them.

**Comment by homestar9** [comment]
Thanks! Very good points.  I'm working on an API wrapper for Experian right now, and oh boy what a headache it has been!

I agree that since named locks are scoped to the server, we should probably initialize the component with some type of unique value which can be used for the lock, like a uuid.  Since API wrappers should be singletons, something like this would ensure that the locking would be unique to the instance in the app:

```
variables._mywrapper_version = '0.0.0'; 
variables._lockName = createUuid();
...

// lock technique to prevent race conditions
lock name="#variables._lockName#" type="exclusive" timeout="30" {
...

```

Good catch on realizing we don't need to re-lock the wrapper when clearing out the token.  Sometimes thinking about all the possible collisions in an app can make my head spin.  It's like trying to figure out a time-travel paradox from Back to the Future. ;)

I'm torn on the issue with `retryOnTokenFailure` because, on one hand, I agree with you that the process should be automatic.  However, there may be occasions when you don't want a particular API call to make a second attempt (perhaps when running tests?).  Making the feature a boolean argument feels to me like it adds a little more flexibility.  Additionally, because we can set the default value of `retryOnTokenFailure` to true, it enables the system to perform re-attempts by default which would be a good thing.  The other reason I added that value is because `apiCall()` is behaving recursively and forcing the value to `false` after the first attempt ensures it doesn't run in an infinite loop.  However that being said, I don't want to overstep and I know the goal of this wrapper is to be as simple and straightforward as possible.  

Here's an example of the part of `apiCall()` without the unnecessary lock and just before the recursive call of the method. I also isolated the code that looks for an authentication failure into a separate private method since most users will want to customize it based on how their particular API behaves:

```
// Check for an expired token error message, and if so, clear out the token and try again;
if ( 
    arguments.retryOnTokenFailure && 
    isAuthenticationFailure( result ) 
) {
        
        clearAuth(); // force auth to reset (clears out the auth token)
        
        // make sure we don't run an infinite loop
        arguments.retryOnTokenFailure = false; 

        // re-run the method recursively
        result = apiCall( argumentCollection = arguments ); 

}
...

private function isAuthenticationFailure( required struct result ) {
    return (
        result.data.error && // was there an error?
        result.data.messages.findNoCase( "Expired Authentication Credentials" ) // each wrapper will have a different value here
    );
}
```

**Comment by mjclemente** [comment]
Apologies again for the lengthy gap in responses! 😞

I like the UUID for the lock and the general restructuring that you've done with the example. That said, after some thinking, I'm not sure I want to include the token-refresh flow in the wrapper. At least not yet. 

My issue is that I'm not comfortable enough with the flow. Usually, if I encounter something I'm not terribly familiar with, I just look around for existing CF tooling from really smart developers like John Berquist, or Matt Gifford, or the folks at Ortus. But I just spent some time on ForgeBox and Github and couldn't find any other examples of CF API wrappers using the refresh-token flow. Maybe you've seen some?

I'd really like to see how other people handle this. I'd also how the flow works in other APIs, because there's bound to be variation, and I'd like the wrapper to be able to handle a fairly wide range of setups, if possible. If they're all wildly different, then maybe it's not a good fit for scaffolding. Right now my only point of reference for how this should look is my limited experience working with the Salesforce API and your work with Experian. I need a little more to go on.

I really like the idea of including this flow. Maybe if you come across an example or two of how it's handled, or of APIs that use it, we could put together something that would be helpful. 

Also, thanks for all the time and thought that you've put into this!

**Comment by homestar9** [comment]
No problem. 

I am also curious about how other people have solved this same problem in their own implementations as I haven't come across any examples yet (even in other languages) so this feels very "homebrew" right now.

I agree that it would probably complicate the scaffolding process as well, so I think it's a good call to omit the extra functionality for now.  Please do reach out if you do find some additional information on the subject as I am always looking to improve my processes and patterns.
